### ISSUE TITLE
pull-right pull left

### ISSUE THREAD

**Issue by naja7host** [morteza/bootstrap-rtl#49] opened 2015-01-05 03:04 UTC
Hello Sir 

i have found some alignement class missedin your css , the class are 

.pull-right{float:left!important}
.pull-left{float:right!important}
.text-right {text-align: left;}
.text-left {text-align: right;}

**Comment by morteza** [comment] 2015-01-05 10:18
Duplicate of #32. The semantic remains the same for `right` and `left`.

**Closed by morteza** 2015-01-05 10:18 UTC
Labels: duplicate

**Comment by mewsoft** [comment] 2015-01-11 12:56
Not correct, try something like this code:
```
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="#">Text link<span class="badge pull-right">7008</span></a></li>
                </ul>
```
we need this to work correct on both LTR and RTL and only adding these classes to the CSS fixed:

```
.pull-right {
  float: left !important;
  }
.pull-left {
  float: right !important;
  }
```

**Comment by mewsoft** [comment] 2015-01-11 13:05
This logic also implemented in another RTL package here:

http://zerox.me/projects/bootstrap3/

Thanks for your nice effort

**Comment by naja7host** [comment] 2015-02-01 20:08
any update in this ? 

we realy need this to be updated in this project . the .text-right and .text-left doesn't support the flip class . 

i as developper , don't want to change the html markup with the inclusion of rtl bootsrap . , one code that can work ib both RTL and LTR .
