### ISSUE TITLE
input group border color

### ISSUE THREAD

**Issue by afattahi54** [morteza/bootstrap-rtl#71] opened 2015-04-15 13:52 UTC
When applying the bootstrap-rtl the input-group border will be override. May be something wrong with

.input-group-addon:first-child{
	border-left:0;
	border-right:1px solid
}

The firebug shows that the bootstrap overrided value is   -moz-use-text-color !!!

I am using bootstrap-rtl-3.3.4-rc1.

PS: This happens for .input-group-addon:last-child too

**Comment by morteza** [comment] 2015-04-15 18:55
Duplicate of #63, #60, #48. It is also mentioned in #66 and several others.

**Closed by morteza** 2015-04-15 18:55 UTC

**Comment by afattahi54** [comment] 2015-04-18 03:39
Thanks! I am testing it on version rtl-3.3.4-rc1, I guessed this have been closed in 3.3.1. Am I correct?! I wonder why I still see this issue in 3.3.4-rc1 :)
